name: e2e-url-checker

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Run URL checker tests
        run: make e2e
